#!/usr/bin/env bash
set -eu

echo "🔵 push"
source hooks/.config

# 1. push all images
IMAGE_NAME="${IMAGE_NAME//index.docker.io\/}"

for arch in ${build_architectures[@]}; do
  echo "✅ Pushing ${IMAGE_NAME}-${arch}"
  echo "⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯"
  echo
  docker exec docker_daemon docker push ${IMAGE_NAME}-${arch}
done

docker exec docker_daemon docker image ls

# 2. build and push manifest
#DOCKER_REPO="index.docker.io/${DOCKER_REPO}"
manifests=""

for arch in ${build_architectures[@]}; do
  manifests="${manifests} ${IMAGE_NAME}-${arch}"
done

echo "✅ Creating manifest ${IMAGE_NAME}"
echo "⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯"
docker exec docker_daemon docker manifest create ${IMAGE_NAME} $manifests
echo

echo "✅ Annotating manifest"
echo "⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯"
for arch in ${build_architectures[@]}; do
    variant=""
    if [ "${docker_to_manifest_variant_map[${arch}]}" != "" ]; then
      variant="--variant ${docker_to_manifest_variant_map[${arch}]}"
    fi
    
    echo "build_architecture= ${arch}"
    echo "arch = ${docker_to_manifest_arch_map[${arch}]}"
    echo "variant= ${docker_to_manifest_variant_map[${arch}]}"
    docker exec docker_daemon docker manifest annotate ${IMAGE_NAME} \
    ${IMAGE_NAME}-${arch} \
    --os linux \
    --arch ${docker_to_manifest_arch_map[${arch}]} \
    ${variant}
done

echo "✅ Inspecting manifest ${IMAGE_NAME}-${arch}"
echo "⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯"
docker exec docker_daemon docker manifest inspect ${IMAGE_NAME}-${arch}
echo

echo "✅ Pushing manifest ${IMAGE_NAME}"
echo "⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯"
docker exec docker_daemon docker manifest push --purge "${IMAGE_NAME}"
echo

echo
echo "😊"